### ISSUE TITLE
Wrong log level?

### ISSUE THREAD

**Issue by dfreudenberger** [ThinkingLogic/kotlin-builder-annotation#22]
Hi,

First of all, thanks for the time you dedicated to this project. It really helped us to make Kotlin data classes more accessible to our java projects.

While executing `mvn clean package -pl web` I get the following output even though the builder is generated correctly.

```
[ERROR] warning: Supported source version 'RELEASE_8' from annotation processor 'org.jetbrains.kotlin.kapt3.base.ProcessorWrapper' less than -source '17'
[ERROR] Note: Generating Builders for 2 classes in /Users/df/dev/event-store-silo/web/target/generated-sources/kaptKotlin/compile
[ERROR] Note: Writing com.rebuy.service.eventstore.web.response.EventDtoBuilder
[ERROR] Note: Adding field: id
[ERROR] Note: Adding field: entityName
[ERROR] Note: Adding field: entityIdentifier
[ERROR] Note: Adding field: eventName
[ERROR] Note: Adding field: employeeId
[ERROR] Note: Adding field: properties
[ERROR] Note: Adding field: createdAt
```

Two questions:
- Is there anything that can be done to get rid of the RELEASE_8 warning?
- Why are those messages reported as errors?

**Comment by YetAnotherMatt** [comment]
Hi @dfreudenberger,
It's good to hear that people are still finding this useful, thanks. I _think_ I was able to fix your first issue by removing support for Java 1.8 (certainly that warning has gone when I run it locally) - version 1.2.2 should be available from Maven shortly.
As regards the other messages - they are written as `NOTE`-level messages to the annotation ProcessingEnvironment. I think it's Maven (and Gradle) that are outputting them at error level. There doesn't appear to be much I can do. There's a good chance it would be fixed by replacing kapt with [KSP](https://kotlinlang.org/docs/ksp-why-ksp.html#comparison-to-kapt), but that requires a substantial rewrite and I really don't know if I'll ever tackle it.
